name: hail
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libstdcxx-ng=9.3.0
  - ncurses=6.2
  - openjdk=8.0.152
  - openssl=1.1.1l
  - pip=21.2.2
  - python=3.7.11
  - readline=8.1
  - setuptools=58.0.4
  - sqlite=3.36.0
  - tk=8.6.11
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aiohttp==3.7.4
    - aiohttp-session==2.7.0
    - async-timeout==3.0.1
    - asyncinit==0.2.4
    - attrs==21.2.0
    - avro==1.10.2
    - azure-core==1.19.0
    - azure-identity==1.6.0
    - azure-storage-blob==12.8.1
    - bokeh==1.4.0
    - boto3==1.19.7
    - botocore==1.22.7
    - cachetools==4.2.4
    - cffi==1.15.0
    - chardet==3.0.4
    - cryptography==35.0.0
    - decorator==4.4.2
    - deprecated==1.2.13
    - dill==0.3.4
    - docutils==0.18
    - elasticsearch==7.9.1
    - fsspec==0.9.0
    - gcsfs==0.8.0
    - google-api-core==1.31.3
    - google-api-python-client==2.28.0
    - google-auth==1.27.0
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==1.7.2
    - google-cloud-storage==1.25.0
    - google-resumable-media==0.5.1
    - googleapis-common-protos==1.53.0
    - hail==0.2.78
    - httplib2==0.20.1
    - humanize==1.0.0
    - hurry-filesize==0.9
    - idna==2.10
    - importlib-metadata==4.8.1
    - isodate==0.6.0
    - janus==0.6.2
    - jinja2==3.0.2
    - jmespath==0.10.0
    - lockfile==0.12.2
    - luigi==2.8.11
    - markupsafe==2.0.1
    - msal==1.16.0
    - msal-extensions==0.3.0
    - msrest==0.6.21
    - multidict==5.2.0
    - nest-asyncio==1.5.1
    - numpy==1.21.3
    - oauthlib==3.1.1
    - packaging==21.2
    - pandas==1.1.4
    - parsimonious==0.8.1
    - pillow==8.4.0
    - portalocker==1.7.1
    - protobuf==3.17.3
    - py4j==0.10.9
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pyjwt==2.3.0
    - pyparsing==2.4.7
    - pyspark==3.1.2
    - python-daemon==2.3.0
    - python-dateutil==2.8.2
    - python-json-logger==0.1.11
    - pytz==2021.3
    - pyyaml==6.0
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - s3transfer==0.5.0
    - scipy==1.7.1
    - six==1.16.0
    - sortedcontainers==2.1.0
    - tabulate==0.8.3
    - tornado==5.1.1
    - tqdm==4.42.1
    - typing-extensions==3.10.0.2
    - ujson==4.2.0
    - uritemplate==4.1.1
    - urllib3==1.26.7
    - wrapt==1.13.3
    - yarl==1.7.0
    - zipp==3.6.0
